using Distributions
using ForwardDiff

integer1 = 1
float1 = 1.0
dual1 = ForwardDiff.GradientNumber(1.0)

integer2 = 2
float2 = 2.0
dual2 = ForwardDiff.GradientNumber(2.0)

arcsine_integer_integer = Arcsine(integer1, integer2)
arcsine_integer_float = Arcsine(integer1, float2)
arcsine_integer_dual = Arcsine(integer1, dual2)
arcsine_float_integer = Arcsine(float1, integer2)
arcsine_float_float = Arcsine(float1, float2)
arcsine_float_dual = Arcsine(float1, dual2)
arcsine_dual_integer = Arcsine(dual1, integer2)
arcsine_dual_float = Arcsine(dual1, float2)
arcsine_dual_dual = Arcsine(dual1, dual2)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(arcsine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(arcsine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(arcsine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(arcsine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(arcsine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(arcsine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(arcsine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(arcsine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(arcsine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(arcsine_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(arcsine_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(arcsine_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(arcsine_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(arcsine_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(arcsine_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(arcsine_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(arcsine_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(arcsine_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(arcsine_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(arcsine_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(arcsine_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(arcsine_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(arcsine_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(arcsine_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(arcsine_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(arcsine_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(arcsine_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(arcsine_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(arcsine_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(arcsine_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(arcsine_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(arcsine_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(arcsine_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(arcsine_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(arcsine_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(arcsine_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(arcsine_dual_dual, eval_at)
println()
println()
println()
println()

