using Distributions
using ForwardDiff

integer = 1
float = 0.5
dualnum = ForwardDiff.GradientNumber(0.5)

bernoulli_integer = Bernoulli(integer)
bernoulli_float = Bernoulli(float)
bernoulli_dual = Bernoulli(dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype ntrials(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype ntrials(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype succprob(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype succprob(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype failprob(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype failprob(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype params(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype params(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype mean(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype mean(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype var(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype var(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype mode(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype mode(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype modes(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype modes(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype median(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype median(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype skewness(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype skewness(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype entropy(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype entropy(bernoulli_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(bernoulli_integer)
println()
println("----float----")
println()
@code_warntype rand(bernoulli_float)
println()
println("----dual----")
println()
@code_warntype rand(bernoulli_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(bernoulli_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(bernoulli_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(bernoulli_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(bernoulli_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(bernoulli_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(bernoulli_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(bernoulli_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(bernoulli_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(bernoulli_dual, eval_at)
println()
println()
println()
println()

