using Distributions
using ForwardDiff

integer = 2
float = 2.0
dual = ForwardDiff.GradientNumber(2.0)

beta_integer_integer = Beta(integer, integer)
beta_integer_float = Beta(integer, float)
beta_integer_dual = Beta(integer, dual)
beta_float_integer = Beta(float, integer)
beta_float_float = Beta(float, float)
beta_float_dual = Beta(float, dual)
beta_dual_integer = Beta(dual, integer)
beta_dual_float = Beta(dual, float)
beta_dual_dual = Beta(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(beta_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(beta_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(beta_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(beta_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(beta_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(beta_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(beta_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(beta_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(beta_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(beta_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(beta_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(beta_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(beta_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(beta_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(beta_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(beta_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(beta_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(beta_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(beta_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(beta_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(beta_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(beta_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(beta_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(beta_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(beta_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(beta_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(beta_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(beta_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(beta_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(beta_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(beta_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(beta_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(beta_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(beta_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(beta_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(beta_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(beta_dual_dual, eval_at)
println()
println()
println()
println()

