using Distributions
using ForwardDiff

integer1 = 1
float1 = 1.0
dual1 = ForwardDiff.GradientNumber(1.0)

integer2 = 2
float2 = 2.0
dual2 = ForwardDiff.GradientNumber(2.0)

betaprime_integer_integer = BetaPrime(integer1, integer2)
betaprime_integer_float = BetaPrime(integer1, float2)
betaprime_integer_dual = BetaPrime(integer1, dual2)
betaprime_float_integer = BetaPrime(float1, integer2)
betaprime_float_float = BetaPrime(float1, float2)
betaprime_float_dual = BetaPrime(float1, dual2)
betaprime_dual_integer = BetaPrime(dual1, integer2)
betaprime_dual_float = BetaPrime(dual1, float2)
betaprime_dual_dual = BetaPrime(dual1, dual2)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(betaprime_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(betaprime_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(betaprime_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(betaprime_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(betaprime_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(betaprime_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(betaprime_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(betaprime_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(betaprime_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(betaprime_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(betaprime_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(betaprime_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(betaprime_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(betaprime_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(betaprime_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(betaprime_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(betaprime_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(betaprime_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(betaprime_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(betaprime_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(betaprime_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(betaprime_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(betaprime_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(betaprime_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(betaprime_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(betaprime_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(betaprime_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(betaprime_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(betaprime_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(betaprime_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(betaprime_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(betaprime_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(betaprime_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(betaprime_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(betaprime_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(betaprime_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(betaprime_dual_dual, eval_at)
println()
println()
println()
println()

