using Distributions
using ForwardDiff

integer = 1
float = 0.5
dualnum = ForwardDiff.GradientNumber(0.5)

binomial_integer = Binomial(2, integer)
binomial_float = Binomial(2, float)
binomial_dual = Binomial(2, dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(binomial_integer)
println()
println("----float----")
println()
@code_warntype ntrials(binomial_float)
println()
println("----dual----")
println()
@code_warntype ntrials(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(binomial_integer)
println()
println("----float----")
println()
@code_warntype succprob(binomial_float)
println()
println("----dual----")
println()
@code_warntype succprob(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(binomial_integer)
println()
println("----float----")
println()
@code_warntype failprob(binomial_float)
println()
println("----dual----")
println()
@code_warntype failprob(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(binomial_integer)
println()
println("----float----")
println()
@code_warntype params(binomial_float)
println()
println("----dual----")
println()
@code_warntype params(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(binomial_integer)
println()
println("----float----")
println()
@code_warntype mean(binomial_float)
println()
println("----dual----")
println()
@code_warntype mean(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(binomial_integer)
println()
println("----float----")
println()
@code_warntype var(binomial_float)
println()
println("----dual----")
println()
@code_warntype var(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(binomial_integer)
println()
println("----float----")
println()
@code_warntype mode(binomial_float)
println()
println("----dual----")
println()
@code_warntype mode(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(binomial_integer)
println()
println("----float----")
println()
@code_warntype modes(binomial_float)
println()
println("----dual----")
println()
@code_warntype modes(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(binomial_integer)
println()
println("----float----")
println()
@code_warntype median(binomial_float)
println()
println("----dual----")
println()
@code_warntype median(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(binomial_integer)
println()
println("----float----")
println()
@code_warntype skewness(binomial_float)
println()
println("----dual----")
println()
@code_warntype skewness(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(binomial_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(binomial_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(binomial_integer)
println()
println("----float----")
println()
@code_warntype entropy(binomial_float)
println()
println("----dual----")
println()
@code_warntype entropy(binomial_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(binomial_integer)
println()
println("----float----")
println()
@code_warntype rand(binomial_float)
println()
println("----dual----")
println()
@code_warntype rand(binomial_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(binomial_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(binomial_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(binomial_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(binomial_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(binomial_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(binomial_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(binomial_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(binomial_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(binomial_dual, eval_at)
println()
println()
println()
println()

