using Distributions
using ForwardDiff

integer = 0.5
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

biweight_integer_integer = Biweight(integer, integer)
biweight_integer_float = Biweight(integer, float)
biweight_integer_dual = Biweight(integer, dual)
biweight_float_integer = Biweight(float, integer)
biweight_float_float = Biweight(float, float)
biweight_float_dual = Biweight(float, dual)
biweight_dual_integer = Biweight(dual, integer)
biweight_dual_float = Biweight(dual, float)
biweight_dual_dual = Biweight(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(biweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(biweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(biweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(biweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(biweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(biweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(biweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(biweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(biweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(biweight_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(biweight_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(biweight_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(biweight_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(biweight_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(biweight_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(biweight_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(biweight_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(biweight_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(biweight_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(biweight_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(biweight_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(biweight_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(biweight_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(biweight_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(biweight_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(biweight_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(biweight_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(biweight_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(biweight_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(biweight_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(biweight_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(biweight_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(biweight_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(biweight_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(biweight_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(biweight_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(biweight_dual_dual, eval_at)
println()
println()
println()
println()

