using Distributions
using ForwardDiff

integer1 = 1
float1 = 1.0
dual1 = ForwardDiff.GradientNumber(1.0)

integer2 = 2
float2 = 2.0
dual2 = ForwardDiff.GradientNumber(2.0)

cauchy_integer_integer = Cauchy(integer1, integer2)
cauchy_integer_float = Cauchy(integer1, float2)
cauchy_integer_dual = Cauchy(integer1, dual2)
cauchy_float_integer = Cauchy(float1, integer2)
cauchy_float_float = Cauchy(float1, float2)
cauchy_float_dual = Cauchy(float1, dual2)
cauchy_dual_integer = Cauchy(dual1, integer2)
cauchy_dual_float = Cauchy(dual1, float2)
cauchy_dual_dual = Cauchy(dual1, dual2)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(cauchy_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(cauchy_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(cauchy_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(cauchy_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(cauchy_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(cauchy_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(cauchy_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(cauchy_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(cauchy_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(cauchy_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(cauchy_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(cauchy_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(cauchy_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(cauchy_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(cauchy_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(cauchy_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(cauchy_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(cauchy_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(cauchy_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(cauchy_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(cauchy_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(cauchy_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(cauchy_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(cauchy_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(cauchy_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(cauchy_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(cauchy_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(cauchy_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(cauchy_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(cauchy_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(cauchy_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(cauchy_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(cauchy_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(cauchy_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(cauchy_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(cauchy_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(cauchy_dual_dual, eval_at)
println()
println()
println()
println()

