using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

chi_integer = Chi(integer)
chi_float = Chi(float)
chi_dual = Chi(dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(chi_integer)
println()
println("----float----")
println()
@code_warntype ntrials(chi_float)
println()
println("----dual----")
println()
@code_warntype ntrials(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(chi_integer)
println()
println("----float----")
println()
@code_warntype succprob(chi_float)
println()
println("----dual----")
println()
@code_warntype succprob(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(chi_integer)
println()
println("----float----")
println()
@code_warntype failprob(chi_float)
println()
println("----dual----")
println()
@code_warntype failprob(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(chi_integer)
println()
println("----float----")
println()
@code_warntype params(chi_float)
println()
println("----dual----")
println()
@code_warntype params(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(chi_integer)
println()
println("----float----")
println()
@code_warntype mean(chi_float)
println()
println("----dual----")
println()
@code_warntype mean(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(chi_integer)
println()
println("----float----")
println()
@code_warntype var(chi_float)
println()
println("----dual----")
println()
@code_warntype var(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(chi_integer)
println()
println("----float----")
println()
@code_warntype mode(chi_float)
println()
println("----dual----")
println()
@code_warntype mode(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(chi_integer)
println()
println("----float----")
println()
@code_warntype modes(chi_float)
println()
println("----dual----")
println()
@code_warntype modes(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(chi_integer)
println()
println("----float----")
println()
@code_warntype median(chi_float)
println()
println("----dual----")
println()
@code_warntype median(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(chi_integer)
println()
println("----float----")
println()
@code_warntype skewness(chi_float)
println()
println("----dual----")
println()
@code_warntype skewness(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(chi_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(chi_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(chi_integer)
println()
println("----float----")
println()
@code_warntype entropy(chi_float)
println()
println("----dual----")
println()
@code_warntype entropy(chi_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(chi_integer)
println()
println("----float----")
println()
@code_warntype rand(chi_float)
println()
println("----dual----")
println()
@code_warntype rand(chi_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(chi_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(chi_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(chi_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(chi_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(chi_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(chi_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(chi_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(chi_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(chi_dual, eval_at)
println()
println()
println()
println()

