using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

chisq_integer = Chisq(integer)
chisq_float = Chisq(float)
chisq_dual = Chisq(dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(chisq_integer)
println()
println("----float----")
println()
@code_warntype ntrials(chisq_float)
println()
println("----dual----")
println()
@code_warntype ntrials(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(chisq_integer)
println()
println("----float----")
println()
@code_warntype succprob(chisq_float)
println()
println("----dual----")
println()
@code_warntype succprob(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(chisq_integer)
println()
println("----float----")
println()
@code_warntype failprob(chisq_float)
println()
println("----dual----")
println()
@code_warntype failprob(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(chisq_integer)
println()
println("----float----")
println()
@code_warntype params(chisq_float)
println()
println("----dual----")
println()
@code_warntype params(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(chisq_integer)
println()
println("----float----")
println()
@code_warntype mean(chisq_float)
println()
println("----dual----")
println()
@code_warntype mean(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(chisq_integer)
println()
println("----float----")
println()
@code_warntype var(chisq_float)
println()
println("----dual----")
println()
@code_warntype var(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(chisq_integer)
println()
println("----float----")
println()
@code_warntype mode(chisq_float)
println()
println("----dual----")
println()
@code_warntype mode(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(chisq_integer)
println()
println("----float----")
println()
@code_warntype modes(chisq_float)
println()
println("----dual----")
println()
@code_warntype modes(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(chisq_integer)
println()
println("----float----")
println()
@code_warntype median(chisq_float)
println()
println("----dual----")
println()
@code_warntype median(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(chisq_integer)
println()
println("----float----")
println()
@code_warntype skewness(chisq_float)
println()
println("----dual----")
println()
@code_warntype skewness(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(chisq_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(chisq_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(chisq_integer)
println()
println("----float----")
println()
@code_warntype entropy(chisq_float)
println()
println("----dual----")
println()
@code_warntype entropy(chisq_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(chisq_integer)
println()
println("----float----")
println()
@code_warntype rand(chisq_float)
println()
println("----dual----")
println()
@code_warntype rand(chisq_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(chisq_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(chisq_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(chisq_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(chisq_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(chisq_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(chisq_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(chisq_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(chisq_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(chisq_dual, eval_at)
println()
println()
println()
println()

