using Distributions
using ForwardDiff

integer = 2
float = 2.0
dual = ForwardDiff.GradientNumber(2.0)

cosine_integer_integer = Cosine(integer, integer)
cosine_integer_float = Cosine(integer, float)
cosine_integer_dual = Cosine(integer, dual)
cosine_float_integer = Cosine(float, integer)
cosine_float_float = Cosine(float, float)
cosine_float_dual = Cosine(float, dual)
cosine_dual_integer = Cosine(dual, integer)
cosine_dual_float = Cosine(dual, float)
cosine_dual_dual = Cosine(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(cosine_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(cosine_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(cosine_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(cosine_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(cosine_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(cosine_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(cosine_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(cosine_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(cosine_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(cosine_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(cosine_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(cosine_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(cosine_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(cosine_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(cosine_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(cosine_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(cosine_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(cosine_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(cosine_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(cosine_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(cosine_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(cosine_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(cosine_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(cosine_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(cosine_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(cosine_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(cosine_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(cosine_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(cosine_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(cosine_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(cosine_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(cosine_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(cosine_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(cosine_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(cosine_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(cosine_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(cosine_dual_dual, eval_at)
println()
println()
println()
println()

