using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

epanechnikov_integer_integer = Epanechnikov(integer, integer)
epanechnikov_integer_float = Epanechnikov(integer, float)
epanechnikov_integer_dual = Epanechnikov(integer, dual)
epanechnikov_float_integer = Epanechnikov(float, integer)
epanechnikov_float_float = Epanechnikov(float, float)
epanechnikov_float_dual = Epanechnikov(float, dual)
epanechnikov_dual_integer = Epanechnikov(dual, integer)
epanechnikov_dual_float = Epanechnikov(dual, float)
epanechnikov_dual_dual = Epanechnikov(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(epanechnikov_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(epanechnikov_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(epanechnikov_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(epanechnikov_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(epanechnikov_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(epanechnikov_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(epanechnikov_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(epanechnikov_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(epanechnikov_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(epanechnikov_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(epanechnikov_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(epanechnikov_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(epanechnikov_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(epanechnikov_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(epanechnikov_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(epanechnikov_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(epanechnikov_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(epanechnikov_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(epanechnikov_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(epanechnikov_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(epanechnikov_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(epanechnikov_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(epanechnikov_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(epanechnikov_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(epanechnikov_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(epanechnikov_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(epanechnikov_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(epanechnikov_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(epanechnikov_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(epanechnikov_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(epanechnikov_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(epanechnikov_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(epanechnikov_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(epanechnikov_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(epanechnikov_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(epanechnikov_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(epanechnikov_dual_dual, eval_at)
println()
println()
println()
println()

