using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

erlang_integer = Erlang(10, integer)
erlang_float = Erlang(10, float)
erlang_dual = Erlang(10, dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(erlang_integer)
println()
println("----float----")
println()
@code_warntype ntrials(erlang_float)
println()
println("----dual----")
println()
@code_warntype ntrials(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(erlang_integer)
println()
println("----float----")
println()
@code_warntype succprob(erlang_float)
println()
println("----dual----")
println()
@code_warntype succprob(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(erlang_integer)
println()
println("----float----")
println()
@code_warntype failprob(erlang_float)
println()
println("----dual----")
println()
@code_warntype failprob(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(erlang_integer)
println()
println("----float----")
println()
@code_warntype params(erlang_float)
println()
println("----dual----")
println()
@code_warntype params(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(erlang_integer)
println()
println("----float----")
println()
@code_warntype mean(erlang_float)
println()
println("----dual----")
println()
@code_warntype mean(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(erlang_integer)
println()
println("----float----")
println()
@code_warntype var(erlang_float)
println()
println("----dual----")
println()
@code_warntype var(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(erlang_integer)
println()
println("----float----")
println()
@code_warntype mode(erlang_float)
println()
println("----dual----")
println()
@code_warntype mode(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(erlang_integer)
println()
println("----float----")
println()
@code_warntype modes(erlang_float)
println()
println("----dual----")
println()
@code_warntype modes(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(erlang_integer)
println()
println("----float----")
println()
@code_warntype median(erlang_float)
println()
println("----dual----")
println()
@code_warntype median(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(erlang_integer)
println()
println("----float----")
println()
@code_warntype skewness(erlang_float)
println()
println("----dual----")
println()
@code_warntype skewness(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(erlang_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(erlang_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(erlang_integer)
println()
println("----float----")
println()
@code_warntype entropy(erlang_float)
println()
println("----dual----")
println()
@code_warntype entropy(erlang_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(erlang_integer)
println()
println("----float----")
println()
@code_warntype rand(erlang_float)
println()
println("----dual----")
println()
@code_warntype rand(erlang_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(erlang_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(erlang_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(erlang_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(erlang_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(erlang_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(erlang_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(erlang_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(erlang_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(erlang_dual, eval_at)
println()
println()
println()
println()

