using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

exponential_integer = Exponential(integer)
exponential_float = Exponential(float)
exponential_dual = Exponential(dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(exponential_integer)
println()
println("----float----")
println()
@code_warntype ntrials(exponential_float)
println()
println("----dual----")
println()
@code_warntype ntrials(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(exponential_integer)
println()
println("----float----")
println()
@code_warntype succprob(exponential_float)
println()
println("----dual----")
println()
@code_warntype succprob(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(exponential_integer)
println()
println("----float----")
println()
@code_warntype failprob(exponential_float)
println()
println("----dual----")
println()
@code_warntype failprob(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(exponential_integer)
println()
println("----float----")
println()
@code_warntype params(exponential_float)
println()
println("----dual----")
println()
@code_warntype params(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(exponential_integer)
println()
println("----float----")
println()
@code_warntype mean(exponential_float)
println()
println("----dual----")
println()
@code_warntype mean(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(exponential_integer)
println()
println("----float----")
println()
@code_warntype var(exponential_float)
println()
println("----dual----")
println()
@code_warntype var(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(exponential_integer)
println()
println("----float----")
println()
@code_warntype mode(exponential_float)
println()
println("----dual----")
println()
@code_warntype mode(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(exponential_integer)
println()
println("----float----")
println()
@code_warntype modes(exponential_float)
println()
println("----dual----")
println()
@code_warntype modes(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(exponential_integer)
println()
println("----float----")
println()
@code_warntype median(exponential_float)
println()
println("----dual----")
println()
@code_warntype median(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(exponential_integer)
println()
println("----float----")
println()
@code_warntype skewness(exponential_float)
println()
println("----dual----")
println()
@code_warntype skewness(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(exponential_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(exponential_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(exponential_integer)
println()
println("----float----")
println()
@code_warntype entropy(exponential_float)
println()
println("----dual----")
println()
@code_warntype entropy(exponential_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(exponential_integer)
println()
println("----float----")
println()
@code_warntype rand(exponential_float)
println()
println("----dual----")
println()
@code_warntype rand(exponential_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(exponential_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(exponential_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(exponential_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(exponential_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(exponential_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(exponential_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(exponential_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(exponential_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(exponential_dual, eval_at)
println()
println()
println()
println()

