using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

fdist_integer_integer = FDist(integer, integer)
fdist_integer_float = FDist(integer, float)
fdist_integer_dual = FDist(integer, dual)
fdist_float_integer = FDist(float, integer)
fdist_float_float = FDist(float, float)
fdist_float_dual = FDist(float, dual)
fdist_dual_integer = FDist(dual, integer)
fdist_dual_float = FDist(dual, float)
fdist_dual_dual = FDist(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(fdist_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(fdist_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(fdist_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(fdist_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(fdist_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(fdist_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(fdist_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(fdist_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(fdist_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(fdist_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(fdist_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(fdist_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(fdist_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(fdist_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(fdist_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(fdist_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(fdist_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(fdist_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(fdist_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(fdist_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(fdist_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(fdist_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(fdist_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(fdist_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(fdist_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(fdist_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(fdist_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(fdist_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(fdist_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(fdist_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(fdist_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(fdist_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(fdist_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(fdist_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(fdist_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(fdist_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(fdist_dual_dual, eval_at)
println()
println()
println()
println()

