using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

fishernoncentralhypergeometric_integer = FisherNoncentralHypergeometric(2, 2, 2, integer)
fishernoncentralhypergeometric_float = FisherNoncentralHypergeometric(2, 2, 2, float)
fishernoncentralhypergeometric_dual = FisherNoncentralHypergeometric(2, 2, 2, dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype ntrials(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype ntrials(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype succprob(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype succprob(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype failprob(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype failprob(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype params(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype params(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype mean(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype mean(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype var(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype var(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype mode(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype mode(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype modes(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype modes(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype median(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype median(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype skewness(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype skewness(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype entropy(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype entropy(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(fishernoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype rand(fishernoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype rand(fishernoncentralhypergeometric_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(fishernoncentralhypergeometric_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(fishernoncentralhypergeometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(fishernoncentralhypergeometric_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(fishernoncentralhypergeometric_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(fishernoncentralhypergeometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(fishernoncentralhypergeometric_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(fishernoncentralhypergeometric_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(fishernoncentralhypergeometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(fishernoncentralhypergeometric_dual, eval_at)
println()
println()
println()
println()

