using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

frechet_integer_integer = Frechet(integer, integer)
frechet_integer_float = Frechet(integer, float)
frechet_integer_dual = Frechet(integer, dual)
frechet_float_integer = Frechet(float, integer)
frechet_float_float = Frechet(float, float)
frechet_float_dual = Frechet(float, dual)
frechet_dual_integer = Frechet(dual, integer)
frechet_dual_float = Frechet(dual, float)
frechet_dual_dual = Frechet(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(frechet_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(frechet_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(frechet_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(frechet_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(frechet_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(frechet_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(frechet_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(frechet_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(frechet_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(frechet_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(frechet_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(frechet_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(frechet_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(frechet_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(frechet_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(frechet_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(frechet_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(frechet_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(frechet_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(frechet_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(frechet_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(frechet_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(frechet_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(frechet_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(frechet_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(frechet_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(frechet_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(frechet_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(frechet_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(frechet_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(frechet_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(frechet_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(frechet_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(frechet_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(frechet_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(frechet_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(frechet_dual_dual, eval_at)
println()
println()
println()
println()

