using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

gamma_integer_integer = Gamma(integer, integer)
gamma_integer_float = Gamma(integer, float)
gamma_integer_dual = Gamma(integer, dual)
gamma_float_integer = Gamma(float, integer)
gamma_float_float = Gamma(float, float)
gamma_float_dual = Gamma(float, dual)
gamma_dual_integer = Gamma(dual, integer)
gamma_dual_float = Gamma(dual, float)
gamma_dual_dual = Gamma(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(gamma_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(gamma_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(gamma_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(gamma_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(gamma_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(gamma_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(gamma_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(gamma_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(gamma_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(gamma_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(gamma_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(gamma_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(gamma_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(gamma_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(gamma_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(gamma_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(gamma_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(gamma_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(gamma_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(gamma_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(gamma_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(gamma_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(gamma_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(gamma_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(gamma_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(gamma_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(gamma_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(gamma_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(gamma_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(gamma_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(gamma_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(gamma_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(gamma_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(gamma_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(gamma_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(gamma_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(gamma_dual_dual, eval_at)
println()
println()
println()
println()

