using Distributions
using ForwardDiff

float = 0.5
dualnum = ForwardDiff.GradientNumber(0.5)

geometric_float = Geometric(float)
geometric_dual = Geometric(dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----float----")
println()
@code_warntype ntrials(geometric_float)
println()
println("----dual----")
println()
@code_warntype ntrials(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----float----")
println()
@code_warntype succprob(geometric_float)
println()
println("----dual----")
println()
@code_warntype succprob(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----float----")
println()
@code_warntype failprob(geometric_float)
println()
println("----dual----")
println()
@code_warntype failprob(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----float----")
println()
@code_warntype params(geometric_float)
println()
println("----dual----")
println()
@code_warntype params(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----float----")
println()
@code_warntype mean(geometric_float)
println()
println("----dual----")
println()
@code_warntype mean(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----float----")
println()
@code_warntype var(geometric_float)
println()
println("----dual----")
println()
@code_warntype var(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----float----")
println()
@code_warntype mode(geometric_float)
println()
println("----dual----")
println()
@code_warntype mode(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----float----")
println()
@code_warntype modes(geometric_float)
println()
println("----dual----")
println()
@code_warntype modes(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----float----")
println()
@code_warntype median(geometric_float)
println()
println("----dual----")
println()
@code_warntype median(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----float----")
println()
@code_warntype skewness(geometric_float)
println()
println("----dual----")
println()
@code_warntype skewness(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----float----")
println()
@code_warntype kurtosis(geometric_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----float----")
println()
@code_warntype entropy(geometric_float)
println()
println("----dual----")
println()
@code_warntype entropy(geometric_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----float----")
println()
@code_warntype rand(geometric_float)
println()
println("----dual----")
println()
@code_warntype rand(geometric_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----float----")
println()
@code_warntype pdf(geometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(geometric_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----float----")
println()
@code_warntype mgf(geometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(geometric_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----float----")
println()
@code_warntype cf(geometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(geometric_dual, eval_at)
println()
println()
println()
println()

