using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

gumbel_integer_integer = Gumbel(integer, integer)
gumbel_integer_float = Gumbel(integer, float)
gumbel_integer_dual = Gumbel(integer, dual)
gumbel_float_integer = Gumbel(float, integer)
gumbel_float_float = Gumbel(float, float)
gumbel_float_dual = Gumbel(float, dual)
gumbel_dual_integer = Gumbel(dual, integer)
gumbel_dual_float = Gumbel(dual, float)
gumbel_dual_dual = Gumbel(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(gumbel_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(gumbel_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(gumbel_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(gumbel_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(gumbel_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(gumbel_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(gumbel_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(gumbel_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(gumbel_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(gumbel_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(gumbel_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(gumbel_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(gumbel_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(gumbel_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(gumbel_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(gumbel_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(gumbel_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(gumbel_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(gumbel_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(gumbel_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(gumbel_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(gumbel_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(gumbel_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(gumbel_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(gumbel_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(gumbel_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(gumbel_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(gumbel_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(gumbel_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(gumbel_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(gumbel_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(gumbel_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(gumbel_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(gumbel_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(gumbel_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(gumbel_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(gumbel_dual_dual, eval_at)
println()
println()
println()
println()

