using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

inversegaussian_integer_integer = InverseGaussian(integer, integer)
inversegaussian_integer_float = InverseGaussian(integer, float)
inversegaussian_integer_dual = InverseGaussian(integer, dual)
inversegaussian_float_integer = InverseGaussian(float, integer)
inversegaussian_float_float = InverseGaussian(float, float)
inversegaussian_float_dual = InverseGaussian(float, dual)
inversegaussian_dual_integer = InverseGaussian(dual, integer)
inversegaussian_dual_float = InverseGaussian(dual, float)
inversegaussian_dual_dual = InverseGaussian(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(inversegaussian_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(inversegaussian_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(inversegaussian_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(inversegaussian_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(inversegaussian_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(inversegaussian_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(inversegaussian_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(inversegaussian_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(inversegaussian_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(inversegaussian_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(inversegaussian_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(inversegaussian_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(inversegaussian_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(inversegaussian_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(inversegaussian_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(inversegaussian_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(inversegaussian_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(inversegaussian_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(inversegaussian_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(inversegaussian_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(inversegaussian_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(inversegaussian_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(inversegaussian_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(inversegaussian_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(inversegaussian_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(inversegaussian_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(inversegaussian_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(inversegaussian_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(inversegaussian_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(inversegaussian_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(inversegaussian_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(inversegaussian_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(inversegaussian_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(inversegaussian_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(inversegaussian_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(inversegaussian_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(inversegaussian_dual_dual, eval_at)
println()
println()
println()
println()

