using Distributions
using ForwardDiff

integer = 2
float = 2.0
dual = ForwardDiff.GradientNumber(2.0)

laplace_integer_integer = Laplace(integer, integer)
laplace_integer_float = Laplace(integer, float)
laplace_integer_dual = Laplace(integer, dual)
laplace_float_integer = Laplace(float, integer)
laplace_float_float = Laplace(float, float)
laplace_float_dual = Laplace(float, dual)
laplace_dual_integer = Laplace(dual, integer)
laplace_dual_float = Laplace(dual, float)
laplace_dual_dual = Laplace(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(laplace_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(laplace_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(laplace_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(laplace_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(laplace_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(laplace_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(laplace_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(laplace_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(laplace_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(laplace_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(laplace_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(laplace_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(laplace_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(laplace_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(laplace_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(laplace_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(laplace_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(laplace_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(laplace_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(laplace_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(laplace_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(laplace_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(laplace_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(laplace_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(laplace_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(laplace_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(laplace_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(laplace_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(laplace_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(laplace_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(laplace_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(laplace_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(laplace_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(laplace_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(laplace_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(laplace_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(laplace_dual_dual, eval_at)
println()
println()
println()
println()

