using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

logistic_integer = Logistic(integer)
logistic_float = Logistic(float)
logistic_dual = Logistic(dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(logistic_integer)
println()
println("----float----")
println()
@code_warntype ntrials(logistic_float)
println()
println("----dual----")
println()
@code_warntype ntrials(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(logistic_integer)
println()
println("----float----")
println()
@code_warntype succprob(logistic_float)
println()
println("----dual----")
println()
@code_warntype succprob(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(logistic_integer)
println()
println("----float----")
println()
@code_warntype failprob(logistic_float)
println()
println("----dual----")
println()
@code_warntype failprob(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(logistic_integer)
println()
println("----float----")
println()
@code_warntype params(logistic_float)
println()
println("----dual----")
println()
@code_warntype params(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(logistic_integer)
println()
println("----float----")
println()
@code_warntype mean(logistic_float)
println()
println("----dual----")
println()
@code_warntype mean(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(logistic_integer)
println()
println("----float----")
println()
@code_warntype var(logistic_float)
println()
println("----dual----")
println()
@code_warntype var(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(logistic_integer)
println()
println("----float----")
println()
@code_warntype mode(logistic_float)
println()
println("----dual----")
println()
@code_warntype mode(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(logistic_integer)
println()
println("----float----")
println()
@code_warntype modes(logistic_float)
println()
println("----dual----")
println()
@code_warntype modes(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(logistic_integer)
println()
println("----float----")
println()
@code_warntype median(logistic_float)
println()
println("----dual----")
println()
@code_warntype median(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(logistic_integer)
println()
println("----float----")
println()
@code_warntype skewness(logistic_float)
println()
println("----dual----")
println()
@code_warntype skewness(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(logistic_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(logistic_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(logistic_integer)
println()
println("----float----")
println()
@code_warntype entropy(logistic_float)
println()
println("----dual----")
println()
@code_warntype entropy(logistic_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(logistic_integer)
println()
println("----float----")
println()
@code_warntype rand(logistic_float)
println()
println("----dual----")
println()
@code_warntype rand(logistic_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(logistic_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(logistic_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(logistic_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(logistic_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(logistic_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(logistic_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(logistic_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(logistic_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(logistic_dual, eval_at)
println()
println()
println()
println()

