using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

lognormal_integer_integer = LogNormal(integer, integer)
lognormal_integer_float = LogNormal(integer, float)
lognormal_integer_dual = LogNormal(integer, dual)
lognormal_float_integer = LogNormal(float, integer)
lognormal_float_float = LogNormal(float, float)
lognormal_float_dual = LogNormal(float, dual)
lognormal_dual_integer = LogNormal(dual, integer)
lognormal_dual_float = LogNormal(dual, float)
lognormal_dual_dual = LogNormal(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(lognormal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(lognormal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(lognormal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(lognormal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(lognormal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(lognormal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(lognormal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(lognormal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(lognormal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(lognormal_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(lognormal_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(lognormal_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(lognormal_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(lognormal_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(lognormal_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(lognormal_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(lognormal_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(lognormal_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(lognormal_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(lognormal_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(lognormal_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(lognormal_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(lognormal_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(lognormal_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(lognormal_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(lognormal_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(lognormal_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(lognormal_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(lognormal_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(lognormal_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(lognormal_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(lognormal_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(lognormal_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(lognormal_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(lognormal_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(lognormal_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(lognormal_dual_dual, eval_at)
println()
println()
println()
println()

