using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

negativebinomial_integer_integer = NegativeBinomial(integer, integer)
negativebinomial_integer_float = NegativeBinomial(integer, float)
negativebinomial_integer_dual = NegativeBinomial(integer, dual)
negativebinomial_float_integer = NegativeBinomial(float, integer)
negativebinomial_float_float = NegativeBinomial(float, float)
negativebinomial_float_dual = NegativeBinomial(float, dual)
negativebinomial_dual_integer = NegativeBinomial(dual, integer)
negativebinomial_dual_float = NegativeBinomial(dual, float)
negativebinomial_dual_dual = NegativeBinomial(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(negativebinomial_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(negativebinomial_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(negativebinomial_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(negativebinomial_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(negativebinomial_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(negativebinomial_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(negativebinomial_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(negativebinomial_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(negativebinomial_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(negativebinomial_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(negativebinomial_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(negativebinomial_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(negativebinomial_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(negativebinomial_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(negativebinomial_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(negativebinomial_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(negativebinomial_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(negativebinomial_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(negativebinomial_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(negativebinomial_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(negativebinomial_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(negativebinomial_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(negativebinomial_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(negativebinomial_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(negativebinomial_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(negativebinomial_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(negativebinomial_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(negativebinomial_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(negativebinomial_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(negativebinomial_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(negativebinomial_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(negativebinomial_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(negativebinomial_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(negativebinomial_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(negativebinomial_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(negativebinomial_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(negativebinomial_dual_dual, eval_at)
println()
println()
println()
println()

