using Distributions
using ForwardDiff

integer = 0.5
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

noncentralt_integer_integer = NoncentralT(integer, integer)
noncentralt_integer_float = NoncentralT(integer, float)
noncentralt_integer_dual = NoncentralT(integer, dual)
noncentralt_float_integer = NoncentralT(float, integer)
noncentralt_float_float = NoncentralT(float, float)
noncentralt_float_dual = NoncentralT(float, dual)
noncentralt_dual_integer = NoncentralT(dual, integer)
noncentralt_dual_float = NoncentralT(dual, float)
noncentralt_dual_dual = NoncentralT(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(noncentralt_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(noncentralt_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(noncentralt_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(noncentralt_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(noncentralt_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(noncentralt_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(noncentralt_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(noncentralt_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(noncentralt_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(noncentralt_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(noncentralt_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(noncentralt_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(noncentralt_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(noncentralt_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(noncentralt_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(noncentralt_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(noncentralt_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(noncentralt_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(noncentralt_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(noncentralt_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(noncentralt_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(noncentralt_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(noncentralt_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(noncentralt_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(noncentralt_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(noncentralt_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(noncentralt_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(noncentralt_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(noncentralt_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(noncentralt_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(noncentralt_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(noncentralt_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(noncentralt_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(noncentralt_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(noncentralt_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(noncentralt_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(noncentralt_dual_dual, eval_at)
println()
println()
println()
println()

