using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

normalcanon_integer_integer = NormalCanon(integer, integer)
normalcanon_integer_float = NormalCanon(integer, float)
normalcanon_integer_dual = NormalCanon(integer, dual)
normalcanon_float_integer = NormalCanon(float, integer)
normalcanon_float_float = NormalCanon(float, float)
normalcanon_float_dual = NormalCanon(float, dual)
normalcanon_dual_integer = NormalCanon(dual, integer)
normalcanon_dual_float = NormalCanon(dual, float)
normalcanon_dual_dual = NormalCanon(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(normalcanon_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(normalcanon_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(normalcanon_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(normalcanon_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(normalcanon_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(normalcanon_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(normalcanon_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(normalcanon_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(normalcanon_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(normalcanon_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(normalcanon_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(normalcanon_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(normalcanon_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(normalcanon_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(normalcanon_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(normalcanon_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(normalcanon_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(normalcanon_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(normalcanon_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(normalcanon_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(normalcanon_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(normalcanon_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(normalcanon_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(normalcanon_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(normalcanon_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(normalcanon_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(normalcanon_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(normalcanon_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(normalcanon_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(normalcanon_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(normalcanon_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(normalcanon_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(normalcanon_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(normalcanon_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(normalcanon_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(normalcanon_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(normalcanon_dual_dual, eval_at)
println()
println()
println()
println()

