using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

integer2 = 3
float2 = 3.0
dualnum2 = ForwardDiff.GradientNumber(3.0)

normalinversegaussian_integer = NormalInverseGaussian(integer, integer2, integer, integer)
normalinversegaussian_float = NormalInverseGaussian(float, float2, float, float)
normalinversegaussian_dual = NormalInverseGaussian(dualnum, dualnum2, dualnum, dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype ntrials(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype ntrials(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype succprob(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype succprob(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype failprob(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype failprob(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype params(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype params(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype mean(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype mean(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype var(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype var(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype mode(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype mode(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype modes(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype modes(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype median(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype median(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype skewness(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype skewness(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype entropy(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype entropy(normalinversegaussian_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(normalinversegaussian_integer)
println()
println("----float----")
println()
@code_warntype rand(normalinversegaussian_float)
println()
println("----dual----")
println()
@code_warntype rand(normalinversegaussian_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(normalinversegaussian_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(normalinversegaussian_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(normalinversegaussian_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(normalinversegaussian_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(normalinversegaussian_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(normalinversegaussian_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(normalinversegaussian_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(normalinversegaussian_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(normalinversegaussian_dual, eval_at)
println()
println()
println()
println()

