using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

normal_integer_integer = Normal(integer, integer)
normal_integer_float = Normal(integer, float)
normal_integer_dual = Normal(integer, dual)
normal_float_integer = Normal(float, integer)
normal_float_float = Normal(float, float)
normal_float_dual = Normal(float, dual)
normal_dual_integer = Normal(dual, integer)
normal_dual_float = Normal(dual, float)
normal_dual_dual = Normal(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(normal_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(normal_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(normal_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(normal_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(normal_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(normal_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(normal_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(normal_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(normal_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(normal_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(normal_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(normal_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(normal_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(normal_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(normal_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(normal_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(normal_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(normal_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(normal_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(normal_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(normal_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(normal_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(normal_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(normal_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(normal_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(normal_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(normal_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(normal_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(normal_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(normal_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(normal_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(normal_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(normal_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(normal_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(normal_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(normal_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(normal_dual_dual, eval_at)
println()
println()
println()
println()

