using Distributions
using ForwardDiff

integer = 1
float = 0.5
dualnum = ForwardDiff.GradientNumber(0.5)

rayleigh_integer = Rayleigh(integer)
rayleigh_float = Rayleigh(float)
rayleigh_dual = Rayleigh(dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype ntrials(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype ntrials(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype succprob(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype succprob(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype failprob(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype failprob(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype params(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype params(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype mean(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype mean(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype var(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype var(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype mode(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype mode(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype modes(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype modes(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype median(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype median(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype skewness(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype skewness(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype entropy(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype entropy(rayleigh_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(rayleigh_integer)
println()
println("----float----")
println()
@code_warntype rand(rayleigh_float)
println()
println("----dual----")
println()
@code_warntype rand(rayleigh_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(rayleigh_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(rayleigh_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(rayleigh_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(rayleigh_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(rayleigh_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(rayleigh_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(rayleigh_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(rayleigh_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(rayleigh_dual, eval_at)
println()
println()
println()
println()

