using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

skellam_integer_integer = Skellam(integer, integer)
skellam_integer_float = Skellam(integer, float)
skellam_integer_dual = Skellam(integer, dual)
skellam_float_integer = Skellam(float, integer)
skellam_float_float = Skellam(float, float)
skellam_float_dual = Skellam(float, dual)
skellam_dual_integer = Skellam(dual, integer)
skellam_dual_float = Skellam(dual, float)
skellam_dual_dual = Skellam(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(skellam_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(skellam_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(skellam_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(skellam_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(skellam_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(skellam_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(skellam_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(skellam_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(skellam_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(skellam_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(skellam_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(skellam_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(skellam_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(skellam_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(skellam_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(skellam_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(skellam_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(skellam_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(skellam_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(skellam_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(skellam_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(skellam_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(skellam_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(skellam_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(skellam_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(skellam_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(skellam_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(skellam_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(skellam_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(skellam_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(skellam_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(skellam_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(skellam_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(skellam_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(skellam_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(skellam_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(skellam_dual_dual, eval_at)
println()
println()
println()
println()

