using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

symtriangular_integer_integer = SymTriangularDist(integer, integer)
symtriangular_integer_float = SymTriangularDist(integer, float)
symtriangular_integer_dual = SymTriangularDist(integer, dual)
symtriangular_float_integer = SymTriangularDist(float, integer)
symtriangular_float_float = SymTriangularDist(float, float)
symtriangular_float_dual = SymTriangularDist(float, dual)
symtriangular_dual_integer = SymTriangularDist(dual, integer)
symtriangular_dual_float = SymTriangularDist(dual, float)
symtriangular_dual_dual = SymTriangularDist(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(symtriangular_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(symtriangular_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(symtriangular_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(symtriangular_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(symtriangular_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(symtriangular_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(symtriangular_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(symtriangular_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(symtriangular_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(symtriangular_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(symtriangular_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(symtriangular_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(symtriangular_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(symtriangular_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(symtriangular_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(symtriangular_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(symtriangular_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(symtriangular_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(symtriangular_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(symtriangular_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(symtriangular_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(symtriangular_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(symtriangular_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(symtriangular_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(symtriangular_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(symtriangular_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(symtriangular_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(symtriangular_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(symtriangular_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(symtriangular_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(symtriangular_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(symtriangular_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(symtriangular_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(symtriangular_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(symtriangular_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(symtriangular_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(symtriangular_dual_dual, eval_at)
println()
println()
println()
println()

