using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

tdist_integer = TDist(integer)
tdist_float = TDist(float)
tdist_dual = TDist(dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(tdist_integer)
println()
println("----float----")
println()
@code_warntype ntrials(tdist_float)
println()
println("----dual----")
println()
@code_warntype ntrials(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(tdist_integer)
println()
println("----float----")
println()
@code_warntype succprob(tdist_float)
println()
println("----dual----")
println()
@code_warntype succprob(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(tdist_integer)
println()
println("----float----")
println()
@code_warntype failprob(tdist_float)
println()
println("----dual----")
println()
@code_warntype failprob(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(tdist_integer)
println()
println("----float----")
println()
@code_warntype params(tdist_float)
println()
println("----dual----")
println()
@code_warntype params(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(tdist_integer)
println()
println("----float----")
println()
@code_warntype mean(tdist_float)
println()
println("----dual----")
println()
@code_warntype mean(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(tdist_integer)
println()
println("----float----")
println()
@code_warntype var(tdist_float)
println()
println("----dual----")
println()
@code_warntype var(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(tdist_integer)
println()
println("----float----")
println()
@code_warntype mode(tdist_float)
println()
println("----dual----")
println()
@code_warntype mode(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(tdist_integer)
println()
println("----float----")
println()
@code_warntype modes(tdist_float)
println()
println("----dual----")
println()
@code_warntype modes(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(tdist_integer)
println()
println("----float----")
println()
@code_warntype median(tdist_float)
println()
println("----dual----")
println()
@code_warntype median(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(tdist_integer)
println()
println("----float----")
println()
@code_warntype skewness(tdist_float)
println()
println("----dual----")
println()
@code_warntype skewness(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(tdist_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(tdist_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(tdist_integer)
println()
println("----float----")
println()
@code_warntype entropy(tdist_float)
println()
println("----dual----")
println()
@code_warntype entropy(tdist_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(tdist_integer)
println()
println("----float----")
println()
@code_warntype rand(tdist_float)
println()
println("----dual----")
println()
@code_warntype rand(tdist_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(tdist_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(tdist_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(tdist_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(tdist_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(tdist_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(tdist_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(tdist_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(tdist_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(tdist_dual, eval_at)
println()
println()
println()
println()

