using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

integer2 = 4
float2 = 4.0
dualnum2 = ForwardDiff.GradientNumber(4.0)

triangular_integer = TriangularDist(integer, integer2, integer)
triangular_float = TriangularDist(float, float2, float)
triangular_dual = TriangularDist(dualnum, dualnum2, dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(triangular_integer)
println()
println("----float----")
println()
@code_warntype ntrials(triangular_float)
println()
println("----dual----")
println()
@code_warntype ntrials(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(triangular_integer)
println()
println("----float----")
println()
@code_warntype succprob(triangular_float)
println()
println("----dual----")
println()
@code_warntype succprob(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(triangular_integer)
println()
println("----float----")
println()
@code_warntype failprob(triangular_float)
println()
println("----dual----")
println()
@code_warntype failprob(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(triangular_integer)
println()
println("----float----")
println()
@code_warntype params(triangular_float)
println()
println("----dual----")
println()
@code_warntype params(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(triangular_integer)
println()
println("----float----")
println()
@code_warntype mean(triangular_float)
println()
println("----dual----")
println()
@code_warntype mean(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(triangular_integer)
println()
println("----float----")
println()
@code_warntype var(triangular_float)
println()
println("----dual----")
println()
@code_warntype var(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(triangular_integer)
println()
println("----float----")
println()
@code_warntype mode(triangular_float)
println()
println("----dual----")
println()
@code_warntype mode(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(triangular_integer)
println()
println("----float----")
println()
@code_warntype modes(triangular_float)
println()
println("----dual----")
println()
@code_warntype modes(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(triangular_integer)
println()
println("----float----")
println()
@code_warntype median(triangular_float)
println()
println("----dual----")
println()
@code_warntype median(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(triangular_integer)
println()
println("----float----")
println()
@code_warntype skewness(triangular_float)
println()
println("----dual----")
println()
@code_warntype skewness(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(triangular_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(triangular_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(triangular_integer)
println()
println("----float----")
println()
@code_warntype entropy(triangular_float)
println()
println("----dual----")
println()
@code_warntype entropy(triangular_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(triangular_integer)
println()
println("----float----")
println()
@code_warntype rand(triangular_float)
println()
println("----dual----")
println()
@code_warntype rand(triangular_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(triangular_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(triangular_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(triangular_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(triangular_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(triangular_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(triangular_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(triangular_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(triangular_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(triangular_dual, eval_at)
println()
println()
println()
println()

