using Distributions
using ForwardDiff

integer = 1
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

triweight_integer_integer = Triweight(integer, integer)
triweight_integer_float = Triweight(integer, float)
triweight_integer_dual = Triweight(integer, dual)
triweight_float_integer = Triweight(float, integer)
triweight_float_float = Triweight(float, float)
triweight_float_dual = Triweight(float, dual)
triweight_dual_integer = Triweight(dual, integer)
triweight_dual_float = Triweight(dual, float)
triweight_dual_dual = Triweight(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(triweight_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(triweight_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(triweight_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(triweight_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(triweight_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(triweight_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(triweight_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(triweight_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(triweight_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(triweight_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(triweight_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(triweight_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(triweight_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(triweight_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(triweight_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(triweight_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(triweight_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(triweight_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(triweight_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(triweight_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(triweight_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(triweight_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(triweight_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(triweight_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(triweight_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(triweight_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(triweight_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(triweight_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(triweight_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(triweight_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(triweight_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(triweight_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(triweight_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(triweight_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(triweight_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(triweight_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(triweight_dual_dual, eval_at)
println()
println()
println()
println()

