using Distributions
using ForwardDiff

integer = 0.5
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

integer2 = 1
float2 = 1.0
dual2 = ForwardDiff.GradientNumber(1.0)

uniform_integer_integer = Uniform(integer, integer2)
uniform_integer_float = Uniform(integer, float2)
uniform_integer_dual = Uniform(integer, dual2)
uniform_float_integer = Uniform(float, integer2)
uniform_float_float = Uniform(float, float2)
uniform_float_dual = Uniform(float, dual2)
uniform_dual_integer = Uniform(dual, integer2)
uniform_dual_float = Uniform(dual, float2)
uniform_dual_dual = Uniform(dual, dual2)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(uniform_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(uniform_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(uniform_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(uniform_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(uniform_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(uniform_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(uniform_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(uniform_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(uniform_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(uniform_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(uniform_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(uniform_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(uniform_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(uniform_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(uniform_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(uniform_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(uniform_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(uniform_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(uniform_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(uniform_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(uniform_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(uniform_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(uniform_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(uniform_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(uniform_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(uniform_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(uniform_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(uniform_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(uniform_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(uniform_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(uniform_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(uniform_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(uniform_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(uniform_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(uniform_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(uniform_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(uniform_dual_dual, eval_at)
println()
println()
println()
println()

