using Distributions
using ForwardDiff

integer = 2
float = 2.0
dualnum = ForwardDiff.GradientNumber(2.0)

walleniusnoncentralhypergeometric_integer = WalleniusNoncentralHypergeometric(2, 2, 2, integer)
walleniusnoncentralhypergeometric_float = WalleniusNoncentralHypergeometric(2, 2, 2, float)
walleniusnoncentralhypergeometric_dual = WalleniusNoncentralHypergeometric(2, 2, 2, dualnum)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype ntrials(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype ntrials(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype ntrials(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype succprob(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype succprob(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype succprob(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype failprob(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype failprob(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype failprob(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype params(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype params(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype params(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mean(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype mean(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype mean(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype var(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype var(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype var(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mode(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype mode(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype mode(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype modes(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype modes(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype modes(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype median(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype median(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype median(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype skewness(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype skewness(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype skewness(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype kurtosis(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype kurtosis(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype kurtosis(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype entropy(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype entropy(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype entropy(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype rand(walleniusnoncentralhypergeometric_integer)
println()
println("----float----")
println()
@code_warntype rand(walleniusnoncentralhypergeometric_float)
println()
println("----dual----")
println()
@code_warntype rand(walleniusnoncentralhypergeometric_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype pdf(walleniusnoncentralhypergeometric_integer, eval_at)
println()
println("----float----")
println()
@code_warntype pdf(walleniusnoncentralhypergeometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype pdf(walleniusnoncentralhypergeometric_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype mgf(walleniusnoncentralhypergeometric_integer, eval_at)
println()
println("----float----")
println()
@code_warntype mgf(walleniusnoncentralhypergeometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype mgf(walleniusnoncentralhypergeometric_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("----integer----")
println()
@code_warntype cf(walleniusnoncentralhypergeometric_integer, eval_at)
println()
println("----float----")
println()
@code_warntype cf(walleniusnoncentralhypergeometric_float, eval_at)
println()
println("----dual----")
println()
@code_warntype cf(walleniusnoncentralhypergeometric_dual, eval_at)
println()
println()
println()
println()

