using Distributions
using ForwardDiff

integer = 0.5
float = 0.5
dual = ForwardDiff.GradientNumber(0.5)

weibull_integer_integer = Weibull(integer, integer)
weibull_integer_float = Weibull(integer, float)
weibull_integer_dual = Weibull(integer, dual)
weibull_float_integer = Weibull(float, integer)
weibull_float_float = Weibull(float, float)
weibull_float_dual = Weibull(float, dual)
weibull_dual_integer = Weibull(dual, integer)
weibull_dual_float = Weibull(dual, float)
weibull_dual_dual = Weibull(dual, dual)

println("____________________________")
println("ntrials")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype ntrials(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype ntrials(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype ntrials(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype ntrials(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype ntrials(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype ntrials(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype ntrials(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype ntrials(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype ntrials(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("succprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype succprob(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype succprob(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype succprob(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype succprob(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype succprob(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype succprob(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype succprob(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype succprob(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype succprob(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("failprob")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype failprob(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype failprob(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype failprob(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype failprob(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype failprob(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype failprob(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype failprob(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype failprob(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype failprob(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("params")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype params(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype params(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype params(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype params(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype params(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype params(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype params(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype params(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype params(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mean")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mean(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mean(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mean(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mean(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mean(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mean(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mean(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mean(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mean(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("var")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype var(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype var(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype var(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype var(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype var(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype var(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype var(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype var(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype var(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("mode")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mode(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype mode(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype mode(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype mode(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype mode(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype mode(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype mode(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype mode(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype mode(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("modes")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype modes(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype modes(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype modes(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype modes(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype modes(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype modes(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype modes(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype modes(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype modes(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("median")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype median(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype median(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype median(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype median(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype median(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype median(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype median(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype median(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype median(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("skewness")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype skewness(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype skewness(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype skewness(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype skewness(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype skewness(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype skewness(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype skewness(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype skewness(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype skewness(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("kurtosis")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype kurtosis(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype kurtosis(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype kurtosis(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype kurtosis(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype kurtosis(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype kurtosis(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype kurtosis(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype kurtosis(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype kurtosis(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("entropy")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype entropy(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype entropy(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype entropy(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype entropy(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype entropy(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype entropy(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype entropy(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype entropy(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype entropy(weibull_dual_dual)
println()
println()
println()
println()

println("____________________________")
println("rand")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype rand(weibull_integer_integer)
println()
println("---- integer, float ----")
println()
@code_warntype rand(weibull_integer_float)
println()
println("---- integer, dual ----")
println()
@code_warntype rand(weibull_integer_dual)
println()
println("---- float, integer ----")
println()
@code_warntype rand(weibull_float_integer)
println()
println("---- float, float ----")
println()
@code_warntype rand(weibull_float_float)
println()
println("---- float, dual ----")
println()
@code_warntype rand(weibull_float_dual)
println()
println("---- dual, integer ----")
println()
@code_warntype rand(weibull_dual_integer)
println()
println("---- dual, float ----")
println()
@code_warntype rand(weibull_dual_float)
println()
println("---- dual, dual ----")
println()
@code_warntype rand(weibull_dual_dual)
println()
println()
println()
println()

eval_at = 2

println("____________________________")
println("pdf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype pdf(weibull_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype pdf(weibull_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype pdf(weibull_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype pdf(weibull_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype pdf(weibull_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype pdf(weibull_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype pdf(weibull_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype pdf(weibull_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype pdf(weibull_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("mgf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype mgf(weibull_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype mgf(weibull_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype mgf(weibull_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype mgf(weibull_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype mgf(weibull_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype mgf(weibull_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype mgf(weibull_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype mgf(weibull_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype mgf(weibull_dual_dual, eval_at)
println()
println()
println()
println()

println("____________________________")
println("cf")
println("____________________________")
println()
println("---- integer, integer ----")
println()
@code_warntype cf(weibull_integer_integer, eval_at)
println()
println("---- integer, float ----")
println()
@code_warntype cf(weibull_integer_float, eval_at)
println()
println("---- integer, dual ----")
println()
@code_warntype cf(weibull_integer_dual, eval_at)
println()
println("---- float, integer ----")
println()
@code_warntype cf(weibull_float_integer, eval_at)
println()
println("---- float, float ----")
println()
@code_warntype cf(weibull_float_float, eval_at)
println()
println("---- float, dual ----")
println()
@code_warntype cf(weibull_float_dual, eval_at)
println()
println("---- dual, integer ----")
println()
@code_warntype cf(weibull_dual_integer, eval_at)
println()
println("---- dual, float ----")
println()
@code_warntype cf(weibull_dual_float, eval_at)
println()
println("---- dual, dual ----")
println()
@code_warntype cf(weibull_dual_dual, eval_at)
println()
println()
println()
println()

